// <auto-generated />
using System;
using MedicalAppointments.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalAppointments.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909190357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Cita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<long>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Citas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Estado = "Programada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1L,
                            Motivo = "Control anual",
                            Observaciones = "",
                            PacienteId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Estado = "Confirmada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1L,
                            Motivo = "Dolor de pecho",
                            Observaciones = "Paciente en ayunas",
                            PacienteId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Estado = "Programada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2L,
                            Motivo = "Consulta pediatrica",
                            Observaciones = "",
                            PacienteId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Estado = "Cancelada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2L,
                            Motivo = "Vacunacion",
                            Observaciones = "Cancelada por el paciente",
                            PacienteId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Estado = "Completada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1L,
                            Motivo = "Seguimiento",
                            Observaciones = "Evolucion favorable",
                            PacienteId = 1L
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Medico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroColegiado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroColegiado")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Email = "carlos.ramirez@clinica.com",
                            Especialidad = "Cardiologia",
                            NombreCompleto = "Dr. Carlos Ramirez",
                            NumeroColegiado = "MED-00123",
                            Telefono = "+593987654322"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Email = "lucia.fernandez@clinica.com",
                            Especialidad = "Pediatria",
                            NombreCompleto = "Dra. Lucia Fernandez",
                            NumeroColegiado = "MED-00456",
                            Telefono = "+593987654333"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Direccion = "Av. Siempre Viva 123",
                            DocumentoIdentidad = "0102030405",
                            Email = "maria.gonzalez@correo.com",
                            FechaNacimiento = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Maria Gonzalez",
                            Telefono = "+593987654321"
                        },
                        new
                        {
                            Id = 2L,
                            Direccion = "Calle Los Pinos 456",
                            DocumentoIdentidad = "0203040506",
                            Email = "jose.martinez@correo.com",
                            FechaNacimiento = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Jose Martinez",
                            Telefono = "+593987654344"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Email = "admin@clinica.com",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Administrador General",
                            PasswordHash = "AQAAAAIAAYagAAAAEAKQgcKVaH2xZAOI5wU/f1ZC++k3OKtbSA3XuD0uWS0kM0IiuML5KoEOwLHB2EZhNQ==",
                            Rol = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Email = "carlos.ramirez@clinica.com",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Dr. Carlos Ramirez",
                            PasswordHash = "AQAAAAIAAYagAAAAEDGhFYvI3j55bxawo11jop0lzoCeIo+LL2J76DigRLHXJq0lYDyxLnhNdiJRuepIGQ==",
                            Rol = "Medico",
                            Username = "medico1"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Email = "ana.torres@clinica.com",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Ana Torres",
                            PasswordHash = "AQAAAAIAAYagAAAAEPzORbcQhDNnOybrBME+81NbJJJKJQEgLVkG91H1VXRGbxv0eo9UQB8nfjvIDBPMaQ==",
                            Rol = "Recepcionista",
                            Username = "recepcionista1"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Cita", b =>
                {
                    b.HasOne("MedicalAppointments.Domain.Entities.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointments.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
