// <auto-generated />
using System;
using MedicalAppointments.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalAppointments.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910190438_AddSeguridadDinamica")]
    partial class AddSeguridadDinamica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Cita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<long>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Citas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DuracionMinutos = 30,
                            Estado = "Programada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1L,
                            MotivoConsulta = "Control anual",
                            PacienteId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DuracionMinutos = 30,
                            Estado = "Confirmada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1L,
                            MotivoConsulta = "Dolor de pecho",
                            PacienteId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            DuracionMinutos = 45,
                            Estado = "Programada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2L,
                            MotivoConsulta = "Consulta pediatrica",
                            PacienteId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DuracionMinutos = 30,
                            Estado = "Cancelada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2L,
                            MotivoCancelacion = "Cancelada por el paciente",
                            MotivoConsulta = "Vacunacion",
                            PacienteId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            DuracionMinutos = 30,
                            Estado = "Completada",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 9, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1L,
                            MotivoConsulta = "Seguimiento",
                            PacienteId = 1L
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Consultorio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Consultorios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Nombre = "Consultorio 101",
                            Ubicacion = "Piso 1 - Ala Norte"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Nombre = "Consultorio 102",
                            Ubicacion = "Piso 1 - Ala Sur"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Nombre = "Consultorio 201",
                            Ubicacion = "Piso 2 - Ala Norte"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.HistorialClinico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("HistorialesClinicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Diagnostico = "Chequeo general - sin hallazgos relevantes",
                            FechaHora = new DateTime(2026, 7, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoNombre = "Dr. Carlos Ramirez",
                            Notas = "Se recomienda control anual.",
                            PacienteId = 1L,
                            Tratamiento = "Ninguno"
                        },
                        new
                        {
                            Id = 2L,
                            Diagnostico = "Hipertension arterial leve",
                            FechaHora = new DateTime(2026, 8, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            MedicoNombre = "Dr. Carlos Ramirez",
                            Notas = "Presion arterial registrada: 135/85 mmHg.",
                            PacienteId = 1L,
                            Tratamiento = "Dieta baja en sodio y control en 3 meses"
                        },
                        new
                        {
                            Id = 3L,
                            Diagnostico = "Control post consulta cardiologica",
                            FechaHora = new DateTime(2026, 9, 5, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            MedicoNombre = "Dra. Lucia Fernandez",
                            Notas = "Paciente estable, sin nuevos sintomas reportados.",
                            PacienteId = 1L,
                            Tratamiento = "Continuar tratamiento habitual"
                        },
                        new
                        {
                            Id = 4L,
                            Diagnostico = "Rinitis alergica estacional",
                            FechaHora = new DateTime(2026, 8, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoNombre = "Dra. Lucia Fernandez",
                            Notas = "Paciente indica mejoria con tratamientos similares previos.",
                            PacienteId = 2L,
                            Tratamiento = "Loratadina 10mg cada 24 horas por 7 dias"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.HorarioAtencion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsultorioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<long>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultorioId");

                    b.HasIndex("MedicoId");

                    b.ToTable("HorariosAtencion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConsultorioId = 1L,
                            DiaSemana = "Lunes",
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            MedicoId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ConsultorioId = 1L,
                            DiaSemana = "Miercoles",
                            HoraFin = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0),
                            MedicoId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ConsultorioId = 2L,
                            DiaSemana = "Martes",
                            HoraFin = new TimeOnly(13, 0, 0),
                            HoraInicio = new TimeOnly(9, 0, 0),
                            MedicoId = 2L
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Medico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroColegiado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroColegiado")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Email = "carlos.ramirez@clinica.com",
                            Especialidad = "Cardiologia",
                            NombreCompleto = "Dr. Carlos Ramirez",
                            NumeroColegiado = "MED-00123",
                            Telefono = "+593987654322"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Email = "lucia.fernandez@clinica.com",
                            Especialidad = "Pediatria",
                            NombreCompleto = "Dra. Lucia Fernandez",
                            NumeroColegiado = "MED-00456",
                            Telefono = "+593987654333"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Alergias = "Alergia a la Penicilina",
                            Direccion = "Av. Siempre Viva 123",
                            DocumentoIdentidad = "0102030405",
                            Email = "maria.gonzalez@correo.com",
                            FechaNacimiento = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Maria Gonzalez",
                            Telefono = "+593987654321"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Alergias = "",
                            Direccion = "Calle Los Pinos 456",
                            DocumentoIdentidad = "0203040506",
                            Email = "jose.martinez@correo.com",
                            FechaNacimiento = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Jose Martinez",
                            Telefono = "+593987654344"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Alergias = "Alergia al Latex",
                            Direccion = "Urbanizacion Las Acacias, Mz 4 Villa 12",
                            DocumentoIdentidad = "0304050607",
                            Email = "ana.herrera@correo.com",
                            FechaNacimiento = new DateTime(1998, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            NombreCompleto = "Ana Sofia Herrera",
                            Telefono = "+593987011223"
                        },
                        new
                        {
                            Id = 4L,
                            Activo = false,
                            Alergias = "",
                            Direccion = "Cdla. La Alborada, Etapa 3",
                            DocumentoIdentidad = "0405060708",
                            Email = "roberto.paredes@correo.com",
                            FechaNacimiento = new DateTime(1972, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NombreCompleto = "Roberto Paredes",
                            Telefono = "+593987223344"
                        },
                        new
                        {
                            Id = 5L,
                            Activo = true,
                            Alergias = "",
                            Direccion = "Av. de las Americas y Rio Amazonas",
                            DocumentoIdentidad = "0506070809",
                            Email = "lucia.mendoza@correo.com",
                            FechaNacimiento = new DateTime(2005, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Otro",
                            NombreCompleto = "Lucia Mendoza",
                            Telefono = "+593987445566"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Permiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Codigo = "usuarios.administrar",
                            Nombre = "Administrar Usuarios"
                        },
                        new
                        {
                            Id = 2L,
                            Codigo = "consultorios.administrar",
                            Nombre = "Administrar Consultorios"
                        },
                        new
                        {
                            Id = 3L,
                            Codigo = "medicos.administrar",
                            Nombre = "Administrar Medicos"
                        },
                        new
                        {
                            Id = 4L,
                            Codigo = "dashboard.ver",
                            Nombre = "Ver Dashboard"
                        },
                        new
                        {
                            Id = 5L,
                            Codigo = "reportes.descargar",
                            Nombre = "Descargar Reportes"
                        },
                        new
                        {
                            Id = 6L,
                            Codigo = "pacientes.escribir",
                            Nombre = "Registrar y Editar Pacientes"
                        },
                        new
                        {
                            Id = 7L,
                            Codigo = "pacientes.leer",
                            Nombre = "Consultar Pacientes"
                        },
                        new
                        {
                            Id = 8L,
                            Codigo = "citas.escribir",
                            Nombre = "Agendar y Cancelar Citas"
                        },
                        new
                        {
                            Id = 9L,
                            Codigo = "citas.leer",
                            Nombre = "Consultar Citas"
                        },
                        new
                        {
                            Id = 10L,
                            Codigo = "historial.escribir",
                            Nombre = "Registrar Historial Clinico"
                        },
                        new
                        {
                            Id = 11L,
                            Codigo = "historial.leer",
                            Nombre = "Consultar Historial Clinico"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Nombre = "Medico"
                        },
                        new
                        {
                            Id = 3L,
                            Nombre = "Recepcionista"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<long>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPermisos", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1L,
                            PermisoId = 1L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 2L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 3L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 4L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 5L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 6L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 7L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 8L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 9L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 10L
                        },
                        new
                        {
                            RolId = 1L,
                            PermisoId = 11L
                        },
                        new
                        {
                            RolId = 2L,
                            PermisoId = 4L
                        },
                        new
                        {
                            RolId = 2L,
                            PermisoId = 7L
                        },
                        new
                        {
                            RolId = 2L,
                            PermisoId = 8L
                        },
                        new
                        {
                            RolId = 2L,
                            PermisoId = 9L
                        },
                        new
                        {
                            RolId = 2L,
                            PermisoId = 10L
                        },
                        new
                        {
                            RolId = 2L,
                            PermisoId = 11L
                        },
                        new
                        {
                            RolId = 3L,
                            PermisoId = 4L
                        },
                        new
                        {
                            RolId = 3L,
                            PermisoId = 5L
                        },
                        new
                        {
                            RolId = 3L,
                            PermisoId = 6L
                        },
                        new
                        {
                            RolId = 3L,
                            PermisoId = 7L
                        },
                        new
                        {
                            RolId = 3L,
                            PermisoId = 8L
                        },
                        new
                        {
                            RolId = 3L,
                            PermisoId = 9L
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MedicoId");

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Email = "admin@clinica.com",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Administrador General",
                            PasswordHash = "$2a$11$hrJzyu02eWYoeV56qp.UHuXAK9qoN2XkIoWD8zpI8/sqi7NCGQB6.",
                            RolId = 1L,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Email = "carlos.ramirez@clinica.com",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicoId = 1L,
                            NombreCompleto = "Dr. Carlos Ramirez",
                            PasswordHash = "$2a$11$sycKZcTlxbtS7uFL3MJjI.AKz4/9PrC/tDa0mxxrrH45aN5t8Djiq",
                            RolId = 2L,
                            Username = "medico1"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Email = "ana.torres@clinica.com",
                            FechaCreacion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Ana Torres",
                            PasswordHash = "$2a$11$kq1G3Pc/8aDOaGHWA1lqtuWvYn.hWbV9uTn.G9o.eOXIMVQI93/VO",
                            RolId = 3L,
                            Username = "recepcionista1"
                        });
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Cita", b =>
                {
                    b.HasOne("MedicalAppointments.Domain.Entities.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointments.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.HistorialClinico", b =>
                {
                    b.HasOne("MedicalAppointments.Domain.Entities.Paciente", "Paciente")
                        .WithMany("HistorialClinico")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.HorarioAtencion", b =>
                {
                    b.HasOne("MedicalAppointments.Domain.Entities.Consultorio", "Consultorio")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("ConsultorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointments.Domain.Entities.Medico", "Medico")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("MedicalAppointments.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalAppointments.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("MedicalAppointments.Domain.Entities.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    // La FK hacia Rol se agrega recien en la migracion
                    // AddForeignKeyUsuariosRoles: en este punto la tabla
                    // Roles todavia no tiene datos sembrados.

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Consultorio", b =>
                {
                    b.Navigation("HorariosAtencion");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("HorariosAtencion");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("HistorialClinico");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("MedicalAppointments.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
