export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './citas.service';
import { CitasService } from './citas.service';
export * from './citas.serviceInterface';
export * from './consultorios.service';
import { ConsultoriosService } from './consultorios.service';
export * from './consultorios.serviceInterface';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './dashboard.serviceInterface';
export * from './historialClinico.service';
import { HistorialClinicoService } from './historialClinico.service';
export * from './historialClinico.serviceInterface';
export * from './medicos.service';
import { MedicosService } from './medicos.service';
export * from './medicos.serviceInterface';
export * from './pacientes.service';
import { PacientesService } from './pacientes.service';
export * from './pacientes.serviceInterface';
export * from './reportes.service';
import { ReportesService } from './reportes.service';
export * from './reportes.serviceInterface';
export * from './seguridad.service';
import { SeguridadService } from './seguridad.service';
export * from './seguridad.serviceInterface';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export * from './usuarios.serviceInterface';
export const APIS = [AuthService, CitasService, ConsultoriosService, DashboardService, HistorialClinicoService, MedicosService, PacientesService, ReportesService, SeguridadService, UsuariosService];
