/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Autentica un usuario y emite un token JWT
     * Valida las credenciales del usuario y retorna un token JWT firmado. El token incluye, entre sus claims, el rol del usuario (Admin, Medico o Recepcionista) para habilitar el control de acceso basado en roles (RBAC) en el resto de la API.
     * @endpoint post /auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

}
