/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CancelarCitaRequest } from '../model/models';
import { CitaCalendarioResponse } from '../model/models';
import { CitaDetalleResponse } from '../model/models';
import { CitasPagedResponse } from '../model/models';
import { CrearCitaRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CitasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Busca citas medicas con filtros avanzados
     * Endpoint de lectura (Query) del patron CQRS que permite buscar citas combinando texto libre, medico, paciente (estos dos ultimos normalmente seleccionados a traves del autocompletado) y un rango de fechas. Todos los parametros son opcionales y combinables. Retorna el listado paginado desde el servidor.
     * @endpoint get /citas/buscar
     * @param palabraClave Texto libre para buscar en el motivo de consulta, el historial clinico, el paciente o el medico
     * @param medicoId Identificador del medico asignado a la cita
     * @param pacienteId Identificador del paciente asociado a la cita
     * @param fechaInicio Fecha inicial del rango de busqueda (inclusive)
     * @param fechaFin Fecha final del rango de busqueda (inclusive)
     * @param pageNumber Numero de pagina a consultar (base 1)
     * @param pageSize Cantidad de registros a retornar por pagina
     */
    buscarCitas(palabraClave?: string, medicoId?: number, pacienteId?: number, fechaInicio?: string, fechaFin?: string, pageNumber?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<CitasPagedResponse>;

    /**
     * Cancela una cita medica existente
     * Endpoint de escritura (Command) del patron CQRS que cambia el estado de la cita a Cancelada y registra el motivo de la cancelacion.
     * @endpoint put /citas/{id}/cancelar
     * @param id Identificador unico del recurso
     * @param cancelarCitaRequest 
     */
    cancelarCita(id: number, cancelarCitaRequest: CancelarCitaRequest, extraHttpRequestParams?: any): Observable<CitaDetalleResponse>;

    /**
     * Agenda una nueva cita medica
     * Endpoint de escritura (Command) del patron CQRS que agenda una nueva cita para un paciente con un medico determinado, resolviendo automaticamente el consultorio fisico asignado al medico segun su horario de atencion. Retorna 400 si la fecha/hora solicitada se encuentra en el pasado, si esta fuera del horario de atencion del medico, si el medico ya tiene otra cita agendada que se solapa con ese rango, o si el consultorio fisico correspondiente ya esta ocupado por otra cita en ese mismo horario.
     * @endpoint post /citas
     * @param crearCitaRequest 
     */
    crearCita(crearCitaRequest: CrearCitaRequest, extraHttpRequestParams?: any): Observable<CitaDetalleResponse>;

    /**
     * Lista citas en formato simplificado para el calendario
     * Endpoint de lectura (Query) optimizado para alimentar directamente un componente de calendario (ej. FullCalendar). Retorna una representacion simplificada de cada cita como evento, opcionalmente acotada a un rango de fechas. El backend intercepta el token JWT del usuario autenticado para aplicar control de acceso: si el rol del usuario es Medico, el sistema ignora cualquier intento de filtrar por otro medico y retorna estrictamente las citas asociadas al MedicoId vinculado a su cuenta de usuario.
     * @endpoint get /citas/calendario
     * @param start Fecha y hora de inicio del rango a consultar (inclusive)
     * @param end Fecha y hora de fin del rango a consultar (inclusive)
     */
    obtenerCitasCalendario(start?: string, end?: string, extraHttpRequestParams?: any): Observable<Array<CitaCalendarioResponse>>;

}
