/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConsultorioRequest } from '../model/models';
import { ConsultorioResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConsultoriosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Actualiza un consultorio existente
     * 
     * @endpoint put /consultorios/{id}
     * @param id Identificador unico del recurso
     * @param consultorioRequest 
     */
    actualizarConsultorio(id: number, consultorioRequest: ConsultorioRequest, extraHttpRequestParams?: any): Observable<ConsultorioResponse>;

    /**
     * Crea un nuevo consultorio
     * 
     * @endpoint post /consultorios
     * @param consultorioRequest 
     */
    crearConsultorio(consultorioRequest: ConsultorioRequest, extraHttpRequestParams?: any): Observable<ConsultorioResponse>;

    /**
     * Da de baja un consultorio
     * Realiza una baja logica del consultorio (lo marca como inactivo), en lugar de eliminarlo fisicamente.
     * @endpoint delete /consultorios/{id}
     * @param id Identificador unico del recurso
     */
    eliminarConsultorio(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Lista todos los consultorios
     * 
     * @endpoint get /consultorios
     */
    listarConsultorios(extraHttpRequestParams?: any): Observable<Array<ConsultorioResponse>>;

}
