/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DashboardMetricas } from '../model/models';
import { DashboardStats } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Obtiene las metricas principales del panel de control
     * Retorna el total de citas de hoy, el total de pacientes registrados y un desglose de citas por estado (pendientes, confirmadas, canceladas).
     * @endpoint get /dashboard/stats
     */
    obtenerEstadisticasDashboard(extraHttpRequestParams?: any): Observable<DashboardStats>;

    /**
     * Obtiene metricas avanzadas del panel de control
     * Retorna un desglose ampliado de indicadores del sistema: citas de hoy, total de pacientes, un resumen de citas por estado y la demanda de citas agrupada por especialidad medica.
     * @endpoint get /dashboard/metricas
     */
    obtenerMetricasDashboard(extraHttpRequestParams?: any): Observable<DashboardMetricas>;

}
