/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HistorialClinicoInput } from '../model/models';
import { HistorialClinicoResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HistorialClinicoServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Agrega una nueva entrada al historial clinico del paciente
     * Permite que un Medico registre una nueva entrada (diagnostico, tratamiento y notas clinicas) en el historial del paciente indicado. Si la peticion incluye \&#39;citaId\&#39;, la cita correspondiente se marca automaticamente como \&#39;Completada\&#39;.
     * @endpoint post /pacientes/{id}/historial
     * @param id Identificador unico del recurso
     * @param historialClinicoInput 
     */
    agregarEntradaHistorialClinico(id: number, historialClinicoInput: HistorialClinicoInput, extraHttpRequestParams?: any): Observable<HistorialClinicoResponse>;

    /**
     * Obtiene el historial clinico completo de un paciente
     * Retorna, en orden cronologico descendente, todas las entradas del historial clinico registradas para el paciente indicado.
     * @endpoint get /pacientes/{id}/historial
     * @param id Identificador unico del recurso
     */
    obtenerHistorialClinico(id: number, extraHttpRequestParams?: any): Observable<Array<HistorialClinicoResponse>>;

}
