/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CrearMedicoRequest } from '../model/models';
import { HorarioAtencionRequest } from '../model/models';
import { HorarioAtencionResponse } from '../model/models';
import { Medico } from '../model/models';
import { MedicoAutocompletado } from '../model/models';
import { MedicoInput } from '../model/models';
import { MedicosPagedResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MedicosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Actualiza un medico existente
     * 
     * @endpoint put /medicos/{id}
     * @param id Identificador unico del recurso
     * @param medicoInput 
     */
    actualizarMedico(id: number, medicoInput: MedicoInput, extraHttpRequestParams?: any): Observable<Medico>;

    /**
     * Asigna un nuevo horario de atencion al medico en un consultorio
     * Registra un rango horario de atencion para el medico indicado en el consultorio especificado. Retorna 400 si el medico ya tiene un horario asignado que se solapa con el rango indicado para ese dia de la semana, o si el consultorio ya esta reservado por otro medico en ese mismo dia y rango horario.
     * @endpoint post /medicos/{id}/horarios
     * @param id Identificador unico del recurso
     * @param horarioAtencionRequest 
     */
    agregarHorarioMedico(id: number, horarioAtencionRequest: HorarioAtencionRequest, extraHttpRequestParams?: any): Observable<HorarioAtencionResponse>;

    /**
     * Autocompleta medicos por nombre
     * Endpoint de lectura ligero pensado para alimentar un componente de autocompletado (typeahead). Retorna una representacion minima de cada medico que coincide parcialmente con el termino ingresado.
     * @endpoint get /medicos/autocompletar
     * @param term Texto parcial ingresado por el usuario para el autocompletado
     */
    autocompletarMedicos(term: string, extraHttpRequestParams?: any): Observable<Array<MedicoAutocompletado>>;

    /**
     * Crea un nuevo medico
     * Registra un nuevo medico y, de forma automatica y transaccional, crea su cuenta de acceso (Usuario) con el rol Medico, enlazada al registro de medico recien creado. Retorna 400 si el username ya esta en uso.
     * @endpoint post /medicos
     * @param crearMedicoRequest 
     */
    crearMedico(crearMedicoRequest: CrearMedicoRequest, extraHttpRequestParams?: any): Observable<Medico>;

    /**
     * Elimina un horario de atencion especifico
     * 
     * @endpoint delete /horarios/{id}
     * @param id Identificador unico del recurso
     */
    eliminarHorarioAtencion(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Elimina un medico
     * 
     * @endpoint delete /medicos/{id}
     * @param id Identificador unico del recurso
     */
    eliminarMedico(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Lista los medicos de forma paginada
     * Retorna el listado de medicos aplicando paginacion desde el servidor (server-side pagination), con busqueda global opcional.
     * @endpoint get /medicos
     * @param pageNumber Numero de pagina a consultar (base 1)
     * @param pageSize Cantidad de registros a retornar por pagina
     * @param searchQuery Texto libre para realizar busquedas parciales por Nombre Completo, Documento de Identidad o Numero de Telefono
     */
    listarMedicos(pageNumber?: number, pageSize?: number, searchQuery?: string, extraHttpRequestParams?: any): Observable<MedicosPagedResponse>;

    /**
     * Obtiene la disponibilidad horaria de un medico
     * Retorna la lista de horarios de atencion y los consultorios fisicos asignados al medico indicado. Accesible para Admin y Recepcionista sin restriccion; un usuario con rol Medico solo puede consultar este recurso cuando el {id} solicitado coincide con su propio MedicoId (retorna 403 en caso contrario).
     * @endpoint get /medicos/{id}/horarios
     * @param id Identificador unico del recurso
     */
    obtenerHorariosMedico(id: number, extraHttpRequestParams?: any): Observable<Array<HorarioAtencionResponse>>;

    /**
     * Obtiene un medico por su identificador
     * 
     * @endpoint get /medicos/{id}
     * @param id Identificador unico del recurso
     */
    obtenerMedicoPorId(id: number, extraHttpRequestParams?: any): Observable<Medico>;

}
