/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Paciente } from '../model/models';
import { PacienteAutocompletado } from '../model/models';
import { PacienteInput } from '../model/models';
import { PagedResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PacientesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Actualiza un paciente existente
     * 
     * @endpoint put /pacientes/{id}
     * @param id Identificador unico del recurso
     * @param pacienteInput 
     */
    actualizarPaciente(id: number, pacienteInput: PacienteInput, extraHttpRequestParams?: any): Observable<Paciente>;

    /**
     * Autocompleta pacientes por nombre
     * Endpoint de lectura ligero pensado para alimentar un componente de autocompletado (typeahead). Retorna una representacion minima de cada paciente que coincide parcialmente con el termino ingresado.
     * @endpoint get /pacientes/autocompletar
     * @param term Texto parcial ingresado por el usuario para el autocompletado
     */
    autocompletarPacientes(term: string, extraHttpRequestParams?: any): Observable<Array<PacienteAutocompletado>>;

    /**
     * Crea un nuevo paciente
     * 
     * @endpoint post /pacientes
     * @param pacienteInput 
     */
    crearPaciente(pacienteInput: PacienteInput, extraHttpRequestParams?: any): Observable<Paciente>;

    /**
     * Elimina un paciente
     * 
     * @endpoint delete /pacientes/{id}
     * @param id Identificador unico del recurso
     */
    eliminarPaciente(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Lista los pacientes de forma paginada
     * Retorna el listado de pacientes aplicando paginacion desde el servidor (server-side pagination).
     * @endpoint get /pacientes
     * @param pageNumber Numero de pagina a consultar (base 1)
     * @param pageSize Cantidad de registros a retornar por pagina
     * @param searchQuery Texto libre para realizar busquedas parciales por Nombre Completo, Documento de Identidad o Numero de Telefono
     */
    listarPacientes(pageNumber?: number, pageSize?: number, searchQuery?: string, extraHttpRequestParams?: any): Observable<PagedResponse>;

    /**
     * Obtiene un paciente por su identificador
     * 
     * @endpoint get /pacientes/{id}
     * @param id Identificador unico del recurso
     */
    obtenerPacientePorId(id: number, extraHttpRequestParams?: any): Observable<Paciente>;

}
