/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface ReportesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Genera el reporte de rendimiento y agenda de un medico
     * Genera un reporte con las citas y el rendimiento del medico indicado dentro del rango de fechas especificado, en el formato solicitado (PDF o Excel). Requiere autenticacion Bearer JWT y el permiso \&#39;reportes.descargar\&#39;.
     * @endpoint get /reportes/medicos/{id}/agenda
     * @param id Identificador unico del recurso
     * @param formato Formato binario en el que se debe generar el reporte
     * @param fechaInicio Fecha inicial del rango de busqueda (inclusive)
     * @param fechaFin Fecha final del rango de busqueda (inclusive)
     */
    generarReporteAgendaMedico(id: number, formato: 'pdf' | 'excel', fechaInicio?: string, fechaFin?: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Genera un reporte de citas en formato Excel
     * Acepta exactamente los mismos filtros que el buscador avanzado de citas y retorna un archivo binario .xlsx con el resultado.
     * @endpoint get /reportes/excel
     * @param palabraClave Texto libre para buscar en el motivo de consulta, el historial clinico, el paciente o el medico
     * @param medicoId Identificador del medico asignado a la cita
     * @param pacienteId Identificador del paciente asociado a la cita
     * @param fechaInicio Fecha inicial del rango de busqueda (inclusive)
     * @param fechaFin Fecha final del rango de busqueda (inclusive)
     */
    generarReporteExcelCitas(palabraClave?: string, medicoId?: number, pacienteId?: number, fechaInicio?: string, fechaFin?: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Genera el historial clinico completo de un paciente en PDF
     * Genera un documento PDF legal e imprimible con el historial clinico completo del paciente indicado (todas sus entradas: diagnostico, tratamiento, notas y medico responsable de cada una). Requiere autenticacion Bearer JWT y el permiso \&#39;reportes.descargar\&#39;.
     * @endpoint get /reportes/pacientes/{id}/historial-pdf
     * @param id Identificador unico del recurso
     */
    generarReporteHistorialPdf(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Genera el reporte de ocupacion de los consultorios fisicos
     * Genera un reporte estadistico en Excel sobre las horas de uso de cada consultorio fisico de la clinica dentro del rango de fechas especificado. Requiere autenticacion Bearer JWT y el permiso \&#39;reportes.descargar\&#39;.
     * @endpoint get /reportes/consultorios/ocupacion
     * @param fechaInicio Fecha inicial del rango de busqueda (inclusive)
     * @param fechaFin Fecha final del rango de busqueda (inclusive)
     */
    generarReporteOcupacionConsultorios(fechaInicio?: string, fechaFin?: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Genera un reporte de citas en formato PDF
     * Acepta exactamente los mismos filtros que el buscador avanzado de citas y retorna un archivo binario .pdf con el resultado.
     * @endpoint get /reportes/pdf
     * @param palabraClave Texto libre para buscar en el motivo de consulta, el historial clinico, el paciente o el medico
     * @param medicoId Identificador del medico asignado a la cita
     * @param pacienteId Identificador del paciente asociado a la cita
     * @param fechaInicio Fecha inicial del rango de busqueda (inclusive)
     * @param fechaFin Fecha final del rango de busqueda (inclusive)
     */
    generarReportePdfCitas(palabraClave?: string, medicoId?: number, pacienteId?: number, fechaInicio?: string, fechaFin?: string, extraHttpRequestParams?: any): Observable<Blob>;

}
