/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActualizarPermisosRolRequest } from '../model/models';
import { PermisoResponse } from '../model/models';
import { RolResponse } from '../model/models';
import { RolUsuario } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SeguridadServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Actualiza los permisos asignados a un rol
     * Reemplaza por completo la configuracion de permisos del rol indicado con el conjunto de identificadores de permisos recibido.
     * @endpoint post /seguridad/roles/{rol}/permisos
     * @param rol Rol sobre el cual se consulta o actualiza la configuracion de permisos
     * @param actualizarPermisosRolRequest 
     */
    actualizarPermisosDeRol(rol: RolUsuario, actualizarPermisosRolRequest: ActualizarPermisosRolRequest, extraHttpRequestParams?: any): Observable<Array<PermisoResponse>>;

    /**
     * Lista todos los permisos disponibles en el sistema
     * Retorna el catalogo completo de permisos que pueden asignarse a cualquier rol, independientemente de cuales esten actualmente activos para alguno de ellos.
     * @endpoint get /seguridad/permisos
     */
    listarPermisos(extraHttpRequestParams?: any): Observable<Array<PermisoResponse>>;

    /**
     * Lista todos los roles disponibles en el sistema
     * Retorna el catalogo de roles (Admin, Medico, Recepcionista) junto con su identificador (RolId), necesario para poder asignar un rol al registrar manualmente un nuevo usuario.
     * @endpoint get /seguridad/roles
     */
    listarRoles(extraHttpRequestParams?: any): Observable<Array<RolResponse>>;

    /**
     * Obtiene los permisos activos de un rol
     * Retorna unicamente los permisos que estan actualmente activos (asignados) para el rol indicado.
     * @endpoint get /seguridad/roles/{rol}/permisos
     * @param rol Rol sobre el cual se consulta o actualiza la configuracion de permisos
     */
    obtenerPermisosDeRol(rol: RolUsuario, extraHttpRequestParams?: any): Observable<Array<PermisoResponse>>;

}
