/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActualizarEstadoUsuarioRequest } from '../model/models';
import { CambiarPasswordRequest } from '../model/models';
import { CrearUsuarioRequest } from '../model/models';
import { UsuarioResponse } from '../model/models';
import { UsuariosPagedResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsuariosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Activa o desactiva la cuenta de un usuario
     * Realiza una baja (o alta) logica de la cuenta del usuario indicado. Requiere el permiso \&#39;usuarios.administrar\&#39;.
     * @endpoint put /usuarios/{id}/estado
     * @param id Identificador unico del recurso
     * @param actualizarEstadoUsuarioRequest 
     */
    actualizarEstadoUsuario(id: number, actualizarEstadoUsuarioRequest: ActualizarEstadoUsuarioRequest, extraHttpRequestParams?: any): Observable<UsuarioResponse>;

    /**
     * Cambia la contrasena del usuario autenticado
     * Endpoint global de autoservicio: cualquier usuario autenticado puede actualizar su propia contrasena enviando su contrasena actual y la nueva. El backend resuelve el identificador del usuario a partir de los Claims de su token JWT (no se recibe por parametro ni por el cuerpo de la peticion), por lo que no requiere ningun permiso administrativo especial.
     * @endpoint put /usuarios/cambiar-password
     * @param cambiarPasswordRequest 
     */
    cambiarPasswordUsuario(cambiarPasswordRequest: CambiarPasswordRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Registra un nuevo usuario en el sistema
     * Crea una nueva cuenta de usuario. Si el RolId indicado corresponde al rol Medico, el MedicoId recibido se vincula obligatoriamente a la cuenta creada, para poder resolver a partir del token JWT a que medico corresponde el usuario autenticado. Requiere el permiso \&#39;usuarios.administrar\&#39;.
     * @endpoint post /usuarios
     * @param crearUsuarioRequest 
     */
    crearUsuario(crearUsuarioRequest: CrearUsuarioRequest, extraHttpRequestParams?: any): Observable<UsuarioResponse>;

    /**
     * Lista los usuarios del sistema de forma paginada
     * Retorna el listado de usuarios aplicando paginacion desde el servidor (server-side pagination), con busqueda global opcional. Requiere el permiso \&#39;usuarios.administrar\&#39;.
     * @endpoint get /usuarios
     * @param pageNumber Numero de pagina a consultar (base 1)
     * @param pageSize Cantidad de registros a retornar por pagina
     * @param searchQuery Texto libre para realizar busquedas parciales por Nombre Completo, Documento de Identidad o Numero de Telefono
     */
    listarUsuarios(pageNumber?: number, pageSize?: number, searchQuery?: string, extraHttpRequestParams?: any): Observable<UsuariosPagedResponse>;

}
