/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Nuevo estado (activo/inactivo) para la cuenta de un usuario
 */
export interface ActualizarEstadoUsuarioRequest { 
    activo: boolean;
}

