/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Nueva configuracion de permisos a asignar a un rol
 */
export interface ActualizarPermisosRolRequest { 
    /**
     * Identificadores de los permisos que quedaran activos para el rol
     */
    permisosIds: Array<number>;
}

