/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para que el usuario autenticado actualice su propia contrasena
 */
export interface CambiarPasswordRequest { 
    passwordActual: string;
    passwordNueva: string;
}

