/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos requeridos para cancelar una cita medica existente
 */
export interface CancelarCitaRequest { 
    motivoCancelacion: string;
}

