/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EstadoCita } from './estadoCita';
import { PacienteResumenCita } from './pacienteResumenCita';
import { MedicoResumenCita } from './medicoResumenCita';


/**
 * Representacion detallada de una cita medica, incluyendo un resumen del paciente y del medico asignados.
 */
export interface CitaDetalleResponse { 
    readonly id: number;
    fechaHora: string;
    motivoConsulta: string;
    estado: EstadoCita;
    paciente: PacienteResumenCita;
    medico: MedicoResumenCita;
}
export namespace CitaDetalleResponse {
}


