/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EstadoCita } from './estadoCita';


/**
 * Representacion simplificada de una cita, lista para dibujarse como evento en un componente de calendario (ej. FullCalendar).
 */
export interface CitaCalendarioResponse { 
    readonly id: number;
    /**
     * Titulo del evento, listo para mostrarse en el calendario
     */
    title: string;
    /**
     * Fecha y hora de inicio de la cita
     */
    start: string;
    /**
     * Fecha y hora de fin estimada de la cita
     */
    end?: string;
    estado: EstadoCita;
    /**
     * Identificador del paciente, necesario para poder consultar su historial clinico desde el detalle del evento
     */
    pacienteId: number;
    pacienteNombre?: string;
    medicoNombre?: string;
}
export namespace CitaCalendarioResponse {
}


