/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paciente } from './paciente';
import { EstadoCita } from './estadoCita';
import { Medico } from './medico';


/**
 * Representa una cita medica. Contiene referencias limpias y completas hacia el paciente y el medico asignados, evitando duplicar su definicion.
 */
export interface Cita { 
    readonly id: number;
    paciente: Paciente;
    medico: Medico;
    fechaHora: string;
    estado: EstadoCita;
    motivo?: string;
    observaciones?: string;
    readonly fechaCreacion?: string;
}
export namespace Cita {
}


