/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CitaInput { 
    pacienteId: number;
    medicoId: number;
    fechaHora: string;
    motivo?: string;
    observaciones?: string;
}

