/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos requeridos para crear o editar un consultorio
 */
export interface ConsultorioRequest { 
    nombre: string;
    ubicacion: string;
}

