/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para registrar manualmente un nuevo usuario en el sistema
 */
export interface CrearUsuarioRequest { 
    nombreCompleto: string;
    username: string;
    password: string;
    /**
     * Identificador del Rol (tabla Roles) que se asignara a esta cuenta
     */
    rolId: number;
    /**
     * Identificador del Medico a vincular con esta cuenta. Obligatorio cuando el RolId corresponde al rol Medico.
     */
    medicoId?: number | null;
}

