/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos requeridos para agendar una nueva cita medica
 */
export interface CrearCitaRequest { 
    pacienteId: number;
    medicoId: number;
    fechaHora: string;
    motivoConsulta: string;
}

