/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para registrar un nuevo medico junto con la cuenta de usuario que le permitira autenticarse en el sistema con el rol Medico.
 */
export interface CrearMedicoRequest { 
    nombreCompleto: string;
    documentoIdentidad: string;
    especialidad: string;
    numeroColegiado: string;
    telefono: string;
    email: string;
    /**
     * Nombre de usuario para la cuenta de acceso del medico
     */
    username: string;
    /**
     * Contrasena inicial de la cuenta de acceso del medico
     */
    password: string;
}

