/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DemandaEspecialidad } from './demandaEspecialidad';
import { ResumenEstadosCitas } from './resumenEstadosCitas';


/**
 * Metricas avanzadas del panel de control
 */
export interface DashboardMetricas { 
    /**
     * Total de citas programadas para el dia de hoy
     */
    citasHoy: number;
    /**
     * Total de pacientes registrados en el sistema
     */
    totalPacientes: number;
    resumenEstados: ResumenEstadosCitas;
    /**
     * Cantidad de citas agendadas por cada especialidad medica
     */
    demandasPorEspecialidad: Array<DemandaEspecialidad>;
}

