/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Metricas principales del panel de control
 */
export interface DashboardStats { 
    /**
     * Total de citas programadas para el dia de hoy
     */
    citasHoy: number;
    /**
     * Total de pacientes registrados en el sistema
     */
    totalPacientes: number;
    /**
     * Citas en estado Programada
     */
    citasPendientes: number;
    /**
     * Citas en estado Confirmada
     */
    citasConfirmadas: number;
    /**
     * Citas en estado Cancelada
     */
    citasCanceladas: number;
}

