/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cantidad de citas agendadas para una especialidad medica
 */
export interface DemandaEspecialidad { 
    especialidad: string;
    totalCitas: number;
}

