/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos requeridos para registrar una nueva entrada del historial clinico
 */
export interface HistorialClinicoInput { 
    diagnostico: string;
    tratamiento?: string;
    notas?: string;
    /**
     * Identificador opcional de la cita medica que origino esta entrada del historial clinico. Cuando se envia, el backend marca automaticamente esa cita como \'Completada\'.
     */
    citaId?: number | null;
}

