/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaSemana } from './diaSemana';


/**
 * Datos requeridos para asignar un rango de disponibilidad horaria
 */
export interface HorarioAtencionRequest { 
    diaSemana: DiaSemana;
    /**
     * Hora de inicio en formato 24 horas (HH:mm)
     */
    horaInicio: string;
    /**
     * Hora de fin en formato 24 horas (HH:mm)
     */
    horaFin: string;
    consultorioId: number;
}
export namespace HorarioAtencionRequest {
}


