/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolUsuario } from './rolUsuario';


export interface LoginResponse { 
    /**
     * Token de acceso JWT
     */
    token: string;
    /**
     * Nombre de usuario utilizado para iniciar sesion
     */
    username: string;
    /**
     * Nombre completo del usuario autenticado
     */
    nombreCompleto: string;
    rol: RolUsuario;
    /**
     * Identificador del registro de Medico vinculado a este usuario, presente unicamente cuando el rol es Medico. Permite al frontend saber si el usuario autenticado es un profesional de la salud y a que medico corresponde.
     */
    medicoId?: number | null;
}
export namespace LoginResponse {
}


