/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para actualizar un medico existente (no modifica su cuenta de acceso)
 */
export interface MedicoInput { 
    nombreCompleto: string;
    documentoIdentidad?: string;
    especialidad: string;
    numeroColegiado: string;
    telefono?: string;
    email?: string;
    activo?: boolean;
}

