/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Representacion completa de un medico
 */
export interface MedicoResponse { 
    readonly id: number;
    nombreCompleto: string;
    documentoIdentidad: string;
    telefono?: string;
    email?: string;
    especialidad: string;
    numeroLicencia: string;
}

