/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelError { 
    /**
     * Descripcion legible del error
     */
    mensaje: string;
    /**
     * Detalles adicionales del error, si aplica
     */
    detalles?: Array<string>;
}

