/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resumen del paciente embebido en el detalle de una cita
 */
export interface PacienteResumenCita { 
    readonly id: number;
    nombreCompleto: string;
    alergias?: string | null;
}

