/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Representacion minima de un paciente para autocompletado
 */
export interface PacienteAutocompletado { 
    readonly id: number;
    nombreCompleto: string;
}

