/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paciente } from './paciente';


/**
 * Respuesta paginada del listado de pacientes (paginacion server-side)
 */
export interface PagedResponse { 
    data: Array<Paciente>;
    /**
     * Numero de pagina actual (base 1)
     */
    pageNumber: number;
    /**
     * Cantidad de registros por pagina
     */
    pageSize: number;
    /**
     * Total de registros existentes en la base de datos
     */
    totalCount: number;
    /**
     * Total de paginas disponibles
     */
    totalPages: number;
}

