/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Un permiso dinamico que puede asignarse a uno o mas roles
 */
export interface PermisoResponse { 
    readonly id: number;
    /**
     * Nombre legible del permiso
     */
    nombre: string;
    /**
     * Codigo unico y estable utilizado por el backend para validar el permiso
     */
    codigo: string;
}

