/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Desglose de citas agrupadas por su estado actual
 */
export interface ResumenEstadosCitas { 
    /**
     * Citas en estado Programada
     */
    pendientes: number;
    /**
     * Citas en estado Confirmada
     */
    confirmadas: number;
    /**
     * Citas en estado Completada
     */
    completadas: number;
    /**
     * Citas en estado Cancelada
     */
    canceladas: number;
}

