/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Rol del usuario, transportado como claim dentro del JWT
 */
export const RolUsuario = {
    Admin: 'Admin',
    Medico: 'Medico',
    Recepcionista: 'Recepcionista',
} as const;
export type RolUsuario = typeof RolUsuario[keyof typeof RolUsuario];

