/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolUsuario } from './rolUsuario';


export interface UsuarioInput { 
    username: string;
    nombreCompleto: string;
    email: string;
    contrasena: string;
    rol: RolUsuario;
    activo?: boolean;
}
export namespace UsuarioInput {
}


