/**
 * API - Sistema de Citas Medicas
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolUsuario } from './rolUsuario';


export interface Usuario { 
    readonly id: number;
    username: string;
    nombreCompleto: string;
    email: string;
    rol: RolUsuario;
    activo: boolean;
    readonly fechaCreacion?: string;
}
export namespace Usuario {
}


