//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace MedicalAppointments.Application.DTOs
{
    using System = global::System;

    

    /// <summary>
    /// Metricas principales del panel de control
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DashboardStats
    {

        /// <summary>
        /// Total de citas programadas para el dia de hoy
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("citasHoy")]
        public int CitasHoy { get; set; } = default!;

        /// <summary>
        /// Total de pacientes registrados en el sistema
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalPacientes")]
        public int TotalPacientes { get; set; } = default!;

        /// <summary>
        /// Citas en estado Programada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("citasPendientes")]
        public int CitasPendientes { get; set; } = default!;

        /// <summary>
        /// Citas en estado Confirmada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("citasConfirmadas")]
        public int CitasConfirmadas { get; set; } = default!;

        /// <summary>
        /// Citas en estado Cancelada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("citasCanceladas")]
        public int CitasCanceladas { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Desglose de citas agrupadas por su estado actual
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ResumenEstadosCitas
    {

        /// <summary>
        /// Citas en estado Programada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pendientes")]
        public int Pendientes { get; set; } = default!;

        /// <summary>
        /// Citas en estado Confirmada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("confirmadas")]
        public int Confirmadas { get; set; } = default!;

        /// <summary>
        /// Citas en estado Completada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("completadas")]
        public int Completadas { get; set; } = default!;

        /// <summary>
        /// Citas en estado Cancelada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("canceladas")]
        public int Canceladas { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Cantidad de citas agendadas para una especialidad medica
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DemandaEspecialidad
    {

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("totalCitas")]
        public int TotalCitas { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Metricas avanzadas del panel de control
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DashboardMetricas
    {

        /// <summary>
        /// Total de citas programadas para el dia de hoy
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("citasHoy")]
        public int CitasHoy { get; set; } = default!;

        /// <summary>
        /// Total de pacientes registrados en el sistema
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalPacientes")]
        public int TotalPacientes { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("resumenEstados")]
        [System.ComponentModel.DataAnnotations.Required]
        public ResumenEstadosCitas ResumenEstados { get; set; } = new ResumenEstadosCitas();

        /// <summary>
        /// Cantidad de citas agendadas por cada especialidad medica
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("demandasPorEspecialidad")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<DemandaEspecialidad> DemandasPorEspecialidad { get; set; } = new System.Collections.ObjectModel.Collection<DemandaEspecialidad>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Rol del usuario, transportado como claim dentro del JWT
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum RolUsuario
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Admin")]
        Admin = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Medico")]
        Medico = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Recepcionista")]
        Recepcionista = 2,

    }

    /// <summary>
    /// Un permiso dinamico que puede asignarse a uno o mas roles
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PermisoResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        /// <summary>
        /// Nombre legible del permiso
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("nombre")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Nombre { get; set; } = default!;

        /// <summary>
        /// Codigo unico y estable utilizado por el backend para validar el permiso
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("codigo")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Codigo { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Un rol del sistema (tabla Roles)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RolResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombre")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Nombre { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Nueva configuracion de permisos a asignar a un rol
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ActualizarPermisosRolRequest
    {

        /// <summary>
        /// Identificadores de los permisos que quedaran activos para el rol
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("permisosIds")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<long> PermisosIds { get; set; } = new System.Collections.ObjectModel.Collection<long>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Estado actual de la cita medica
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum EstadoCita
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Programada")]
        Programada = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Confirmada")]
        Confirmada = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Cancelada")]
        Cancelada = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Completada")]
        Completada = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"NoAsistio")]
        NoAsistio = 4,

    }

    /// <summary>
    /// Genero del paciente
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GeneroPaciente
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Masculino")]
        Masculino = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Femenino")]
        Femenino = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Otro")]
        Otro = 2,

    }

    /// <summary>
    /// Dia de la semana para la disponibilidad horaria de un medico
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DiaSemana
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Lunes")]
        Lunes = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Martes")]
        Martes = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Miercoles")]
        Miercoles = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Jueves")]
        Jueves = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Viernes")]
        Viernes = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"Sabado")]
        Sabado = 5,

    }

    /// <summary>
    /// Consultorio fisico donde se atienden las citas medicas
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConsultorioResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombre")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Nombre { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("ubicacion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Ubicacion { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = true;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos requeridos para crear o editar un consultorio
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConsultorioRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("nombre")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Nombre { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("ubicacion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Ubicacion { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representacion completa de un medico
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MedicoResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("documentoIdentidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DocumentoIdentidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("telefono")]
        public string Telefono { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("numeroLicencia")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NumeroLicencia { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos requeridos para asignar un rango de disponibilidad horaria
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HorarioAtencionRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("diaSemana")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DiaSemana>))]
        public DiaSemana DiaSemana { get; set; } = default!;

        /// <summary>
        /// Hora de inicio en formato 24 horas (HH:mm)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("horaInicio")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^([01]\d|2[0-3]):[0-5]\d$")]
        public string HoraInicio { get; set; } = default!;

        /// <summary>
        /// Hora de fin en formato 24 horas (HH:mm)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("horaFin")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^([01]\d|2[0-3]):[0-5]\d$")]
        public string HoraFin { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("consultorioId")]
        public long ConsultorioId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Un rango de disponibilidad horaria asignado a un medico en un consultorio especifico
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HorarioAtencionResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("medicoId")]
        public long MedicoId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("diaSemana")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DiaSemana>))]
        public DiaSemana DiaSemana { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("horaInicio")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string HoraInicio { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("horaFin")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string HoraFin { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("consultorio")]
        [System.ComponentModel.DataAnnotations.Required]
        public ConsultorioResponse Consultorio { get; set; } = new ConsultorioResponse();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Error
    {

        /// <summary>
        /// Descripcion legible del error
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mensaje")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Mensaje { get; set; } = default!;

        /// <summary>
        /// Detalles adicionales del error, si aplica
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("detalles")]
        public System.Collections.Generic.ICollection<string> Detalles { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginRequest
    {

        /// <summary>
        /// Correo electronico o nombre de usuario
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("usuario")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Usuario { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("contrasena")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Contrasena { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginResponse
    {

        /// <summary>
        /// Token de acceso JWT
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("token")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token { get; set; } = default!;

        /// <summary>
        /// Nombre de usuario utilizado para iniciar sesion
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        /// <summary>
        /// Nombre completo del usuario autenticado
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("rol")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RolUsuario>))]
        public RolUsuario Rol { get; set; } = default!;

        /// <summary>
        /// Identificador del registro de Medico vinculado a este usuario, presente unicamente cuando el rol es Medico. Permite al frontend saber si el usuario autenticado es un profesional de la salud y a que medico corresponde.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("medicoId")]
        public long? MedicoId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representacion de una cuenta de usuario del sistema
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UsuarioResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        /// <summary>
        /// Nombre del rol asignado a esta cuenta
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("rolNombre")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RolNombre { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = true;

        /// <summary>
        /// Identificador del registro de Medico vinculado a esta cuenta, presente unicamente cuando el rol asignado es Medico
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("medicoId")]
        public long? MedicoId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos para registrar manualmente un nuevo usuario en el sistema
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CrearUsuarioRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 6)]
        public string Password { get; set; } = default!;

        /// <summary>
        /// Identificador del Rol (tabla Roles) que se asignara a esta cuenta
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("rolId")]
        public long RolId { get; set; } = default!;

        /// <summary>
        /// Identificador del Medico a vincular con esta cuenta. Obligatorio cuando el RolId corresponde al rol Medico.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("medicoId")]
        public long? MedicoId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Nuevo estado (activo/inactivo) para la cuenta de un usuario
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ActualizarEstadoUsuarioRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos para que el usuario autenticado actualice su propia contrasena
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CambiarPasswordRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("passwordActual")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PasswordActual { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("passwordNueva")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 6)]
        public string PasswordNueva { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Respuesta paginada del listado de usuarios (paginacion server-side)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UsuariosPagedResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<UsuarioResponse> Data { get; set; } = new System.Collections.ObjectModel.Collection<UsuarioResponse>();

        /// <summary>
        /// Numero de pagina actual (base 1)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageNumber")]
        public int PageNumber { get; set; } = default!;

        /// <summary>
        /// Cantidad de registros por pagina
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        /// <summary>
        /// Total de registros existentes en la base de datos
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalCount")]
        public int TotalCount { get; set; } = default!;

        /// <summary>
        /// Total de paginas disponibles
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalPages")]
        public int TotalPages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Paciente
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("documentoIdentidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DocumentoIdentidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("fechaNacimiento")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTime FechaNacimiento { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("telefono")]
        public string Telefono { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("direccion")]
        public string Direccion { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = true;

        [System.Text.Json.Serialization.JsonPropertyName("genero")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GeneroPaciente>))]
        public GeneroPaciente Genero { get; set; } = default!;

        /// <summary>
        /// Texto libre para registrar alergias u otras condiciones de alerta medica del paciente
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("alergias")]
        public string? Alergias { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representacion minima de un paciente para autocompletado
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PacienteAutocompletado
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Respuesta paginada del listado de pacientes (paginacion server-side)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PagedResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Paciente> Data { get; set; } = new System.Collections.ObjectModel.Collection<Paciente>();

        /// <summary>
        /// Numero de pagina actual (base 1)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageNumber")]
        public int PageNumber { get; set; } = default!;

        /// <summary>
        /// Cantidad de registros por pagina
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        /// <summary>
        /// Total de registros existentes en la base de datos
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalCount")]
        public int TotalCount { get; set; } = default!;

        /// <summary>
        /// Total de paginas disponibles
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalPages")]
        public int TotalPages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Respuesta paginada del listado de medicos (paginacion server-side)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MedicosPagedResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Medico> Data { get; set; } = new System.Collections.ObjectModel.Collection<Medico>();

        /// <summary>
        /// Numero de pagina actual (base 1)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageNumber")]
        public int PageNumber { get; set; } = default!;

        /// <summary>
        /// Cantidad de registros por pagina
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        /// <summary>
        /// Total de registros existentes en la base de datos
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalCount")]
        public int TotalCount { get; set; } = default!;

        /// <summary>
        /// Total de paginas disponibles
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalPages")]
        public int TotalPages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Respuesta paginada del buscador avanzado de citas (paginacion server-side)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CitasPagedResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Cita> Data { get; set; } = new System.Collections.ObjectModel.Collection<Cita>();

        /// <summary>
        /// Numero de pagina actual (base 1)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageNumber")]
        public int PageNumber { get; set; } = default!;

        /// <summary>
        /// Cantidad de registros por pagina
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        /// <summary>
        /// Total de registros existentes que cumplen los criterios de busqueda
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalCount")]
        public int TotalCount { get; set; } = default!;

        /// <summary>
        /// Total de paginas disponibles
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalPages")]
        public int TotalPages { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PacienteInput
    {

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("documentoIdentidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DocumentoIdentidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("fechaNacimiento")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTime FechaNacimiento { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("telefono")]
        public string Telefono { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("direccion")]
        public string Direccion { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = true;

        [System.Text.Json.Serialization.JsonPropertyName("genero")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GeneroPaciente>))]
        public GeneroPaciente Genero { get; set; } = default!;

        /// <summary>
        /// Texto libre para registrar alergias u otras condiciones de alerta medica del paciente
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("alergias")]
        public string? Alergias { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Medico
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("documentoIdentidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DocumentoIdentidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("numeroColegiado")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NumeroColegiado { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("telefono")]
        public string Telefono { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = true;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representacion minima de un medico para autocompletado
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MedicoAutocompletado
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos para actualizar un medico existente (no modifica su cuenta de acceso)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MedicoInput
    {

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("documentoIdentidad")]
        public string DocumentoIdentidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("numeroColegiado")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NumeroColegiado { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("telefono")]
        public string Telefono { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activo")]
        public bool Activo { get; set; } = true;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos para registrar un nuevo medico junto con la cuenta de usuario que le permitira autenticarse en el sistema con el rol Medico.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CrearMedicoRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("documentoIdentidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DocumentoIdentidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("numeroColegiado")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NumeroColegiado { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("telefono")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Telefono { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; } = default!;

        /// <summary>
        /// Nombre de usuario para la cuenta de acceso del medico
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; } = default!;

        /// <summary>
        /// Contrasena inicial de la cuenta de acceso del medico
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 6)]
        public string Password { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representa una cita medica. Contiene referencias limpias y completas hacia el paciente y el medico asignados, evitando duplicar su definicion.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Cita
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("paciente")]
        [System.ComponentModel.DataAnnotations.Required]
        public Paciente Paciente { get; set; } = new Paciente();

        [System.Text.Json.Serialization.JsonPropertyName("medico")]
        [System.ComponentModel.DataAnnotations.Required]
        public Medico Medico { get; set; } = new Medico();

        [System.Text.Json.Serialization.JsonPropertyName("fechaHora")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset FechaHora { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("estado")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EstadoCita>))]
        public EstadoCita Estado { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("motivo")]
        public string Motivo { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("observaciones")]
        public string Observaciones { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("fechaCreacion")]
        public System.DateTimeOffset FechaCreacion { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos requeridos para agendar una nueva cita medica
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CrearCitaRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("pacienteId")]
        public long PacienteId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("medicoId")]
        public long MedicoId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("fechaHora")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset FechaHora { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("motivoConsulta")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string MotivoConsulta { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos requeridos para cancelar una cita medica existente
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CancelarCitaRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("motivoCancelacion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string MotivoCancelacion { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Resumen del paciente embebido en el detalle de una cita
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PacienteResumenCita
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("alergias")]
        public string? Alergias { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Resumen del medico embebido en el detalle de una cita
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MedicoResumenCita
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nombreCompleto")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NombreCompleto { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("especialidad")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Especialidad { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representacion detallada de una cita medica, incluyendo un resumen del paciente y del medico asignados.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CitaDetalleResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("fechaHora")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset FechaHora { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("motivoConsulta")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string MotivoConsulta { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("estado")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EstadoCita>))]
        public EstadoCita Estado { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("paciente")]
        [System.ComponentModel.DataAnnotations.Required]
        public PacienteResumenCita Paciente { get; set; } = new PacienteResumenCita();

        [System.Text.Json.Serialization.JsonPropertyName("medico")]
        [System.ComponentModel.DataAnnotations.Required]
        public MedicoResumenCita Medico { get; set; } = new MedicoResumenCita();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Representacion simplificada de una cita, lista para dibujarse como evento en un componente de calendario (ej. FullCalendar).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CitaCalendarioResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        /// <summary>
        /// Titulo del evento, listo para mostrarse en el calendario
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        /// <summary>
        /// Fecha y hora de inicio de la cita
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("start")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset Start { get; set; } = default!;

        /// <summary>
        /// Fecha y hora de fin estimada de la cita
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("end")]
        public System.DateTimeOffset End { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("estado")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EstadoCita>))]
        public EstadoCita Estado { get; set; } = default!;

        /// <summary>
        /// Identificador del paciente, necesario para poder consultar su historial clinico desde el detalle del evento
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pacienteId")]
        public long PacienteId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("pacienteNombre")]
        public string PacienteNombre { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("medicoNombre")]
        public string MedicoNombre { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Una entrada del historial clinico de un paciente
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HistorialClinicoResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        /// <summary>
        /// Fecha y hora en que se registro la entrada clinica
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("fechaHora")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset FechaHora { get; set; } = default!;

        /// <summary>
        /// Nombre del medico que registro la entrada
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("medicoNombre")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string MedicoNombre { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("diagnostico")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Diagnostico { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tratamiento")]
        public string Tratamiento { get; set; } = default!;

        /// <summary>
        /// Notas clinicas adicionales del medico
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("notas")]
        public string Notas { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Datos requeridos para registrar una nueva entrada del historial clinico
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HistorialClinicoInput
    {

        [System.Text.Json.Serialization.JsonPropertyName("diagnostico")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Diagnostico { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tratamiento")]
        public string Tratamiento { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("notas")]
        public string Notas { get; set; } = default!;

        /// <summary>
        /// Identificador opcional de la cita medica que origino esta entrada del historial clinico. Cuando se envia, el backend marca automaticamente esa cita como 'Completada'.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("citaId")]
        public long? CitaId { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Formato
    {

        [System.Runtime.Serialization.EnumMember(Value = @"pdf")]
        Pdf = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"excel")]
        Excel = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTime>
    {
        public override System.DateTime Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTime.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTime value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileResponse : System.IDisposable
    {
        private System.IDisposable? _client;
        private System.IDisposable? _response;

        public int StatusCode { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public System.IO.Stream Stream { get; private set; }

        public bool IsPartial
        {
            get { return StatusCode == 206; }
        }

        public FileResponse(int statusCode, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.IO.Stream stream, System.IDisposable? client, System.IDisposable? response)
        {
            StatusCode = statusCode;
            Headers = headers;
            Stream = stream;
            _client = client;
            _response = response;
        }

        public void Dispose()
        {
            Stream.Dispose();
            if (_response != null)
                _response.Dispose();
            if (_client != null)
                _client.Dispose();
        }
    }



}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765